# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace # trims trailing whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline
      - id: check-yaml # checks syntax of yaml files
      - id: check-json # checks syntax of json files
      - id: check-toml # checks syntax of toml files
      - id: debug-statements # Check for debugger imports and py37+ breakpoint() calls in python source.
      - id: check-added-large-files # prevent giant files from being committed
      - id: fix-encoding-pragma # removes "# -*- coding: utf-8 -*-" from python files (since we only support python 3)
        args: [--remove]
      - id: check-merge-conflict # check for files that contain merge conflict strings
  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
