# Generated by Django 3.2.11 on 2021-12-23 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("taggit", "0003_taggeditem_add_unique_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type",
                    models.CharField(
                        choices=[("free", "Free"), ("quote", "Quote")],
                        default="free",
                        max_length=10,
                        verbose_name="Experience Type",
                    ),
                ),
                ("description", models.TextField(verbose_name="Experience Description")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="Experience publish time")),
            ],
        ),
        migrations.CreateModel(
            name="ExperienceComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField(verbose_name="Comment")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="Comment publish time")),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="experience.experience"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="ExperienceCategory",
            fields=[
                ("is_published", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, verbose_name="Category Name")),
                ("slug", models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ("description", models.TextField(blank=True, default="", verbose_name="Category Description")),
                ("create_at", models.DateTimeField(auto_now_add=True, verbose_name="Experience publish time")),
                (
                    "user",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="experience",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="experience.experiencecategory",
                verbose_name="Experience Category",
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
