# Generated by Django 3.2.12 on 2022-02-09 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField(verbose_name="Experience Description")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Experience publish time")),
            ],
            options={
                "verbose_name": "Experience",
                "verbose_name_plural": "Experiences",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExperienceCategory",
            fields=[
                ("name", models.CharField(max_length=100, verbose_name="Category Name")),
                ("slug", models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ("description", models.TextField(blank=True, default="", verbose_name="Category Description")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Experience publish time")),
            ],
            options={
                "verbose_name": "Experience Category",
                "verbose_name_plural": "Experience Categories",
            },
        ),
        migrations.CreateModel(
            name="ExperienceComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("comment", models.TextField(verbose_name="Comment")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Comment publish time")),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="experience.experience"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Experience Comment",
                "verbose_name_plural": "Experience Comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="experience",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="experience.experiencecategory",
                verbose_name="Experience Category",
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
