# Generated by Django 3.2.11 on 2021-12-16 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', verbose_name='Category Description')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('free', 'Free'), ('quote', 'Quote')], default='free', max_length=10, verbose_name='Experience Type')),
                ('author_name', models.CharField(max_length=100, verbose_name='Author Name')),
                ('title', models.CharField(max_length=100, verbose_name='Experience Title')),
                ('subtitle', models.CharField(blank=True, default='', max_length=100, verbose_name='Experience Subtitle')),
                ('description', models.TextField(verbose_name='Experience Description')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Experience publish time')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience.experiencecategory', verbose_name='Experience Category')),
            ],
        ),
    ]
