# Generated by Django 3.2.11 on 2021-12-30 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterModelOptions(
            name='experiencecategory',
            options={'verbose_name': 'Experience Category', 'verbose_name_plural': 'Experience Categories'},
        ),
        migrations.AlterModelOptions(
            name='experiencecomment',
            options={'verbose_name': 'Experience Comment', 'verbose_name_plural': 'Experience Comments'},
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='experiencecategory',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='experiencecomment',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='experiencecategory',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='experiencecategory',
            name='user',
        ),
    ]
