# Generated by Django 3.2.11 on 2022-01-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_auto_20211230_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-created_at'], 'verbose_name': 'Experience', 'verbose_name_plural': 'Experiences'},
        ),
        migrations.AlterModelOptions(
            name='experiencecomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Experience Comment', 'verbose_name_plural': 'Experience Comments'},
        ),
    ]
