# Generated by Django 3.2.11 on 2022-02-08 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_auto_20220106_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='type',
        ),
    ]
